
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
 
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("3.0.1.18108")]